export const GAP = 0.06;
export const TILE_PITCH = 0.353;
export const POST_WIDTH = 0.095;
export const TRALL_THICKNESS = 0.028;
export const SHED_DEPTH = 2.67;

export const POST_HOLE_SIZE = 0.17;

export const ENCLOSURE_WIDTH_TILES = 11;
export const ENCLOSURE_DEPTH_TILES = 7;
export const STRIP_WIDTH_TILES = 4;
export const STRIP_ROWS_TILES = 5;

export const PATH_CONNECTOR_TILES = 4;

const PLATTA_THICKNESS = 0.05;
export const STENMJOL_THICKNESS = 0.03;
export const BARLAGER_THICKNESS = 0.1;
export const SCHAKT_DEPTH = PLATTA_THICKNESS + STENMJOL_THICKNESS + BARLAGER_THICKNESS;

export const ENCLOSURE_WIDTH = ENCLOSURE_WIDTH_TILES * TILE_PITCH;
export const ENCLOSURE_DEPTH = ENCLOSURE_DEPTH_TILES * TILE_PITCH;
export const STRIP_WIDTH = STRIP_WIDTH_TILES * TILE_PITCH;
export const STRIP_LENGTH = STRIP_ROWS_TILES * TILE_PITCH;
export const PATH_CONNECTOR_LENGTH = PATH_CONNECTOR_TILES * TILE_PITCH;
export const PATH_CONNECTOR_WIDTH = TILE_PITCH / 2;

export const EXISTING_STUD_DISTANCE = 3.93;

const MAX_POST_SPACING = 1.8;

const EAST_POST_COUNT = Math.ceil((ENCLOSURE_DEPTH + POST_WIDTH) / MAX_POST_SPACING);
const SOUTH_POST_COUNT = Math.ceil((ENCLOSURE_WIDTH - STRIP_WIDTH) / MAX_POST_SPACING) + 1;

const FENCE_CORNER_X = EXISTING_STUD_DISTANCE + POST_WIDTH / 2;
const FENCE_CORNER_Y = SHED_DEPTH - POST_WIDTH / 2 - TRALL_THICKNESS;

export const ENCLOSURE_OFFSET_X = FENCE_CORNER_X - ENCLOSURE_WIDTH - POST_WIDTH / 2;
export const ENCLOSURE_OFFSET_Y = FENCE_CORNER_Y - ENCLOSURE_DEPTH - POST_WIDTH / 2;

const eastPosts = Array.from({ length: EAST_POST_COUNT }, (_, i) => ({
	x: FENCE_CORNER_X,
	y: ENCLOSURE_OFFSET_Y + ((FENCE_CORNER_Y - ENCLOSURE_OFFSET_Y) * (i + 1)) / EAST_POST_COUNT
}));
const southPosts = Array.from({ length: SOUTH_POST_COUNT - 1 }, (_, i) => ({
	x:
		ENCLOSURE_OFFSET_X +
		STRIP_WIDTH +
		POST_WIDTH / 2 +
		(i * (ENCLOSURE_WIDTH - STRIP_WIDTH)) / (SOUTH_POST_COUNT - 1),
	y: FENCE_CORNER_Y
}));

export const POSTS = [...eastPosts, ...southPosts];

export const FENCE = {
	corner: { x: FENCE_CORNER_X, y: FENCE_CORNER_Y },
	anchor: { x: FENCE_CORNER_X, y: POST_WIDTH / 2 }
};
